app/Http/routes.php
<?php

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
Route::get('home', 'backend\JamaahController@dasboard');
Route::get('/', 'backend\JamaahController@index');
Route::get('dasboard', 'backend\JamaahController@dasboard');
// Jamaah
Route::resource('jamaah', 'backend\JamaahController');
Route::get('hapusjamaah/{id}', array('as' => 'destroyjamaah', 'uses' => 'backend\JamaahController@destroy'));

// Keuangan Anggota
Route::resource('keuanganasuransi', 'backend\KeuanganAsuransiController');
Route::get('hapuskeuanganasuransi/{id}', array('as' => 'destroykeuanganasuransi', 'uses' => 'backend\KeuanganAsuransiController@destroy'));

// Penempatan Makam
Route::resource('penempatan', 'backend\PivotController');
Route::get('hapuspenempatan/{id}', array('as' => 'destroypenempatan', 'uses' => 'backend\PivotController@destroy'));

// Keuangan Kapling
Route::resource('keuangankapling', 'backend\KeuanganKaplingController');
Route::get('hapuskeuangankapling/{id}', array('as' => 'destroykeuangankapling', 'uses' => 'backend\KeuanganKaplingController@destroy'));

// Booking Kapling
Route::resource('bookingkapling', 'backend\BookingKaplingController');
Route::get('hapusbookingkapling/{id}', array('as' => 'destroybookingkapling', 'uses' => 'backend\BookingKaplingController@destroy'));

// Unit Makam
Route::resource('unit', 'backend\UnitController');
Route::get('hapusunit/{id}', array('as' => 'destroyunit', 'uses' => 'backend\UnitController@destroy'));

// Kapling Makam
Route::resource('kapling', 'backend\KaplingController');
Route::get('hapuskapling/{id}', array('as' => 'destroykapling', 'uses' => 'backend\KaplingController@destroy'));

// Penanggung Jawab
Route::resource('penanggungjawab', 'backend\PenanggungController');
Route::get('hapuspenanggungjawab/{id}', array('as' => 'destroypenanggungjawab', 'uses' => 'backend\PenanggungController@destroy'));

resources/views/Makam/Penempatan/edit.blade.php
@extends('layouts.master')
@section('title') Edit @stop
@section('subtitle') Jamaah Yang Menempati Makam @stop
@section('content')
<div class="portlet box purple">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-gift"></i>Edit Nama Penempat Makam : {{ $penempat->Jamaah->NamaJamaah }} || Lokasi : {{ $penempat->Kapling->Unit->Lokasi }} || Kode Kapling{{ $penempat->Kapling->KodeKapling }}
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
		</div>
	</div>
	<div class="portlet-body form">
		{!! Form::model($penempat,['method' => 'PATCH','route'=>['penempatan.update',$penempat->id]]) !!}
			<meta name="csrf-token" content="{{ csrf_token() }}" />
			<div class="form-group form-md-line-input">
				<label class="col-md-2 control-label">Nama Jamaah</label>
				<div class="col-md-4">
					<select class="form-control select2me" name="id_jamaah">
						@foreach ($jamaah as $data)
							<option value="{{ $data->id }}">{{ $data->NamaJamaah }}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="form-group form-md-line-input">
				<label class="col-md-2 control-label">Lokasi & Kode Kapling</label>
				<div class="col-md-4">
					<select class="form-control select2me" name="id_kapling">
						@foreach ($kapling as $data)
							<option value="{{ $data->id }}">{{ $data->Unit->Lokasi }} - {{ $data->KodeKapling }}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="form-actions">
				<div class="row">
					<div class="col-md-offset-2 col-md-10">
						<button type="submit" class="btn blue">Edit</button>
					</div>
				</div>
			</div>
		{!! Form::close() !!}
	</div>
</div>
@stop

resources/views/Makam/Penempatan/index.blade.php
@extends('layouts.master')
@section('title') Data @stop
@section('subtitle') Jamaah Yang Menempati Makam @stop
@section('content')

<div class="portlet box purple">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-gift"></i>Informasi
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<ul class="nav nav-pills">
			<li class="active">
				<a href="#tab_2_1" data-toggle="tab">
				Data Jamaah</a>
			</li>
			<li>
				<a href="#tab_2_2" data-toggle="tab">
				Tambah Jamaah Yang Menempati Makam</a>
			</li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade active in" id="tab_2_1">
				<div class="data-table"></div>
				<table class="table table-striped table-bordered table-hover" id="aktif">
					<thead>
					<tr>
						<th>#</th>
						<th>Nama Jamaah</th>
						<th>Lokasi Makam</th>
						<th>Kode Kapling</th>
						<th>Aksi</th>
					</tr>
					</thead>
					<tbody>
						<?php
							$no = 1;
						?>
						<tr>
						@foreach ($penempat as $data)
							<td>{{ $no++ }} </td>
							<td>{{ $data->Jamaah->NamaJamaah }} </td>
							<td>{{ $data->Kapling->Unit->Lokasi }} </td>
							<td>{{ $data->Kapling->KodeKapling }} </td>
							<td>
								<a href="{{route('jamaah.show',$data->Jamaah->id)}}" class="btn btn-primary">Rician</a>
								<!-- <a href="{{route('penempatan.edit',$data->id)}}" class="btn btn-warning">Update</a> -->
								<a href="{{route('destroypenempatan',$data->id)}}" class="btn btn-danger">Hapus</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
			<div class="tab-pane fade" id="tab_2_2">
				<div class="portlet-body form">
					{!! Form::open(array('route' => 'penempatan.store', 'class' => 'form-horizontal', 'id' => 'Tambah')) !!}
						<meta name="csrf-token" content="{{ csrf_token() }}" />
						<div class="form-group form-md-line-input">
							<label class="col-md-2 control-label">Nama Jamaah</label>
							<div class="col-md-4">
								<select class="form-control select2me" name="id_jamaah">
									@foreach ($jamaah as $data)
										<option value="{{ $data->id }}">{{ $data->NamaJamaah }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-group form-md-line-input">
							<label class="col-md-2 control-label">Lokasi & Kode Kapling</label>
							<div class="col-md-4">
								<select class="form-control select2me" name="id_kapling">
									@foreach ($kapling as $data)
										<option value="{{ $data->id }}">{{ $data->Unit->Lokasi }} - {{ $data->KodeKapling }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-2 col-md-10">
									<button type="submit" class="btn blue">Submit</button>
								</div>
							</div>
						</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@stop
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
	$(document).ready(function(){
		$('#aktif').DataTable({
			// optional
			"pagingType": "full_numbers",
			stateSave: true,
			"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
		});
    });
    </script>