app/Http/routes.php
<?php

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
Route::get('home', 'backend\JamaahController@dasboard');
Route::get('/', 'backend\JamaahController@index');
Route::get('dasboard', 'backend\JamaahController@dasboard');
// Jamaah
Route::resource('jamaah', 'backend\JamaahController');
Route::get('hapusjamaah/{id}', array('as' => 'destroyjamaah', 'uses' => 'backend\JamaahController@destroy'));

// Keuangan Anggota
Route::resource('keuanganasuransi', 'backend\KeuanganAsuransiController');
Route::get('hapuskeuanganasuransi/{id}', array('as' => 'destroykeuanganasuransi', 'uses' => 'backend\KeuanganAsuransiController@destroy'));

// Penempatan Makam
Route::resource('penempatan', 'backend\PivotController');
Route::get('hapuspenempatan/{id}', array('as' => 'destroypenempatan', 'uses' => 'backend\PivotController@destroy'));

// Keuangan Kapling
Route::resource('keuangankapling', 'backend\KeuanganKaplingController');
Route::get('hapuskeuangankapling/{id}', array('as' => 'destroykeuangankapling', 'uses' => 'backend\KeuanganKaplingController@destroy'));

// Booking Kapling
Route::resource('bookingkapling', 'backend\BookingKaplingController');
Route::get('hapusbookingkapling/{id}', array('as' => 'destroybookingkapling', 'uses' => 'backend\BookingKaplingController@destroy'));

// Unit Makam
Route::resource('unit', 'backend\UnitController');
Route::get('hapusunit/{id}', array('as' => 'destroyunit', 'uses' => 'backend\UnitController@destroy'));

// Kapling Makam
Route::resource('kapling', 'backend\KaplingController');
Route::get('hapuskapling/{id}', array('as' => 'destroykapling', 'uses' => 'backend\KaplingController@destroy'));

// Penanggung Jawab
Route::resource('penanggungjawab', 'backend\PenanggungController');
Route::get('hapuspenanggungjawab/{id}', array('as' => 'destroypenanggungjawab', 'uses' => 'backend\PenanggungController@destroy'));

resources/views/Makam/Lokasi/edit.blade.php
@extends('layouts.master')
@section('title') Edit @stop
@section('subtitle') Lokasi Makam @stop
@section('content')
<div class="portlet box purple">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-gift"></i>Edit Lokasi Makam : {{ $unit->Lokasi }}
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<div class="portlet-body form">
			{!! Form::model($unit,['method' => 'PATCH','route'=>['unit.update',$unit->id]]) !!}
				<meta name="csrf-token" content="{{ csrf_token() }}" />
				<div class="form-body">
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label">Lokasi Makam</label>
						<div class="col-md-10">
							<input type="text" class="form-control" name="Lokasi" value="{{ $unit->Lokasi }}">
							<div class="form-control-focus">
							</div>
						</div>
					</div>
				</div>
				<div class="form-body">
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label">Kapasitas Makam</label>
						<div class="col-md-10">
							<input type="text" class="form-control" name="KapasitasMakam" value="{{ $unit->KapasitasMakam }}">
							<div class="form-control-focus">
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions">
					<div class="row">
						<div class="col-md-offset-2 col-md-10">
							<button type="submit" class="btn blue">Edit</button>
						</div>
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
@stop

resources/views/Makam/Lokasi/index.blade.php
@extends('layouts.master')
@section('title') Data @stop
@section('subtitle') Lokasi Makam @stop
@section('content')
<div class="portlet box purple">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-gift"></i>Unit
		</div>
		<div class="tools">
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>
		</div>
	</div>
	<div class="portlet-body">
		<ul class="nav nav-pills">
			<li class="active">
				<a href="#tab_2_1" data-toggle="tab">
				Data Makam</a>
			</li>
			<li>
				<a href="#tab_2_2" data-toggle="tab">
				Tambah Lokasi Makam</a>
			</li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade active in" id="tab_2_1">
				<div class="data-table"></div>
				<table class="table table-striped table-bordered table-hover" id="aktif">
					<thead>
					<?php
						$no = 1;
					?>
					<tr>
						<th>#</th>
						<th>Lokasi</th>
						<th>Kapasitas Makam</th>
						<th>Kapling Kosong</th>
						<th>Aksi</th>
					</tr>
					</thead>
					@foreach ($unit as $data)
					<tbody>
							<td>{{ $no++ }}</td>
							<td>{{ $data->Lokasi }}</td>
							<td>{{ $data->KapasitasMakam }} Unit</td>
							<td> Unit</td>
							<td>
								<a href="{{route('unit.show',$data->id)}}" class="btn btn-primary">Lihat Rincian</a>
								<a href="{{route('unit.edit',$data->id)}}" class="btn btn-warning">Edit Lokasi</a>
								<a href="{{route('destroyunit',$data->id)}}" class="btn btn-danger">Hapus</a>
							</td>
					</tbody>
					@endforeach
				</table>
			</div>
			<div class="tab-pane fade" id="tab_2_2">
				<div class="portlet-body form">
					{!! Form::open(array('route' => 'unit.store', 'class' => 'form-horizontal', 'id' => 'Tambah')) !!}
						<meta name="csrf-token" content="{{ csrf_token() }}" />
						<div class="form-body">
							<div class="form-group form-md-line-input">
								<label class="col-md-2 control-label">Lokasi Makam</label>
								<div class="col-md-10">
									<input type="text" class="form-control" name="Lokasi">
									<div class="form-control-focus">
									</div>
								</div>
							</div>
						</div>
						<div class="form-body">
							<div class="form-group form-md-line-input">
								<label class="col-md-2 control-label">Kapasitas Makam</label>
								<div class="col-md-10">
									<input type="text" class="form-control" name="KapasitasMakam">
									<div class="form-control-focus">
									</div>
								</div>
							</div>
						</div>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-offset-2 col-md-10">
									<button type="submit" class="btn blue">Submit</button>
								</div>
							</div>
						</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@stop
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
    <script>
	$(document).ready(function(){
		$('#aktif').DataTable({
			// optional
			"pagingType": "full_numbers",
			stateSave: true,
			"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
		});
    });

	/*Validation*/
	
    </script>

resources/views/Makam/Lokasi/show.blade.php
@extends('layouts.master')
@section('title') Data @stop
@section('subtitle') Lokasi Makam {{ $unit->Lokasi }} @stop
@section('content')
<div class="row">
	<div class="col-md-4">
		<div class="portlet box red-sunglo">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-child "></i>Informasi Unit Makam
				</div>
			</div>
			<div class="portlet-body">
				<ul>
					<li>
						 Nama Lokasi : <b> {!! $unit->Lokasi !!} </b>
					</li>
					<li>
						 Kapasitas Makam : {!! $unit->KapasitasMakam !!}
					</li>
				</ul>
			</div>
		</div>
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-cogs"></i>Kapling Yang Belum Terdata
				</div>
			</div>
			<div class="portlet-body">
				<h3>Sisa: {!! $unit->KapasitasMakam - $sisa !!} </h3>
				{!! $persen = ($sisa / $unit->KapasitasMakam) * 100 !!}% Complete
				<div class="progress progress-striped active">
					<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{!! $unit->KapasitasMakam - $sisa !!}" aria-valuemin="0" aria-valuemax="$unit->KapasitasMakam" style="width: {!! $persen !!}%">
						<span class="sr-only">{!! $persen !!}% Complete (success)</span>
					</div>
				</div>
			</div>
		</div>
		<div class="portlet box blue">
			<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-gift"></i>Tambah Kapling
			</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				@if (($unit->KapasitasMakam - $sisa)>0)
				{!! Form::open(array('route' => 'kapling.store', 'class' => 'form-horizontal form-row-seperated')) !!}
					<meta name="csrf-token" content="{{ csrf_token() }}" />
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3">Lokasi Makam</label>
							<div class="col-md-9">
								<select class="bs-select form-control" data-show-subtext="true" name='id_unit' readonly>
		        					<option value="{!! $unit->id !!}">{!! $unit->Lokasi !!}
		        					</option>
		        				</select>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">Kode</label>
							<div class="col-md-9">
								{!! Form::text('KodeKapling', Input::old('KodeKapling'), array('class' => 'form-control' , 'placeholder' => 'Contoh : 100')) !!}
							</div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green"><i class="fa fa-pencil"></i> Tambah</button>
							</div>
						</div>
					</div>
				{!! Form::close() !!}
				@else
				<br><H2><center>Sudah Terdata Semua</center></H2><br>
				@endif
				
				<!-- END FORM-->
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="portlet box blue tabbable">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>Detail Unit Makam
				</div>
			</div>
			<div class="portlet-body">
				<div class="data-table"></div>
					<table class="table table-striped table-hover" id="kapling">
						<thead>
						<tr>
							<th>Kode Kapling</th>
							<th>Nama Jamaah Meninggal </th>
						</tr>
						</thead>
						<tbody>
							@foreach($kapling as $data)
								<tr>
									<td>{!! $data->KodeKapling !!}
										<a href="{!! route('kapling.edit', $data->idk) !!}" class="btn btn-xs yellow">Update</i></a>
									</td>
									<td>@if($data->nama != '')
											{!! $data->nama !!}
											<a href="{!! route('jamaah.show', $data->idjamaah) !!}" class="btn btn-primary">Rincian</i></a>
											<a href="{!! route('jamaah.edit', $data->idjamaah) !!}" class="btn btn-warning">Update</i></a>
										@else
											Kosong
										@endif()
									</td>
									<!-- <td>
										<a href="{!! route('kapling.edit', $data->idk) !!}" class="btn btn-xs yellow">
											Edit <i class="fa fa-edit"></i>
										</a>
										<a href="{!! route('destroykapling', $data->idk) !!}" class="btn btn-xs red">
											Hapus <i class="fa fa-times"></i>
										</a>
									</td> -->
								</tr>
							@endforeach
						</tbody>
					</table>
			</div>
		</div>
	</div>
</div>
@stop
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
    <script>
	$(document).ready(function(){
		$('#kapling').DataTable({
			// optional
			"pagingType": "full_numbers",
			stateSave: true,
			"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
		});
    });

	/*Validation*/
	
    </script>